CREATE TABLE Clientes (
    ID INTEGER NOT NULL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Tipo CHAR(1) NOT NULL,
    CPF_CNPJ VARCHAR(20) NOT NULL,
    RG_IE VARCHAR(20),
    DataCadastro DATE DEFAULT CURRENT_DATE,
    Ativo SMALLINT NOT NULL
);

create generator gen_clientes_id;

CREATE TRIGGER TR_CLIENTES FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    new.ID = gen_id(gen_clientes_id, 1);
END;

CREATE TABLE Telefones (
    ID INTEGER NOT NULL PRIMARY KEY,
    ClienteID INTEGER NOT NULL,
    DDD VARCHAR(2) NOT NULL,
    Numero VARCHAR(20) NOT NULL,
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ID) ON DELETE CASCADE
);

create generator gen_telefones_id;

CREATE TRIGGER TR_TELEFONES FOR TELEFONES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    new.ID = gen_id(gen_telefones_id, 1);
END;

CREATE TABLE Enderecos (
    ID INTEGER NOT NULL PRIMARY KEY,
    ClienteID INTEGER NOT NULL,
    Logradouro VARCHAR(200) NOT NULL,
    Numero VARCHAR(10) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado VARCHAR(2) NOT NULL,
    Pais VARCHAR(100) NOT NULL,
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ID) ON DELETE CASCADE
);

create generator gen_enderecos_id;

CREATE TRIGGER TR_ENDERECOS FOR ENDERECOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    new.ID = gen_id(gen_enderecos_id, 1);
END;

ALTER TABLE CLIENTES
ADD CONSTRAINT UNIQUE_DOCUMENT UNIQUE (CPF_CNPJ);